.de Id
.ds Rv \\$3
.ds Dt \\$4
..
.Id $Id: xmountains.man,v 1.2 1994/01/24 18:12:31 spb Exp $
.ds r \s-1RCS\s0
.if n .ds - \%--
.if t .ds - \(em
.TH XMOUNTAINS 1 
.SH NAME
xmountains \- A fractal landscape generator.
.SH SYNOPSIS
.B xmountains
[
.B bxmslrftISTRapgd
]

.SH DESCRIPTION
.B xmountains
is a X11 based fractal landscape generator.
It generates random fractal surfaces and displays them in a window.
While the program is running the fractal is continuously extended on the right
and the image is scrolled from left to right to expose the newly generated area.

.PP
Flags:
.br
.B \-b 
.RS
Use the root window.
.RE
.br
.B \-x 
.RS
Start the fractal from a flat start.
.RE
.br
.B \-m 
.RS
Display a map of the surface rather than a perspective view.
.RE
.br
.B \-s 
.RS
Toggle the smoothing algorithm. Without smoothing the program runs twice as fast but the surface is covered in creases.
.RE
.br
.B \-l [9] 
.RS
Set the width of the surface. Increasing this value by one doubles the width of the surface.
.RE
.br
.B \-t [1] 
.RS
Set the number of non\-fractal iterations. Increasing this value by one doubles the average number of mountains across the width of the surface.
.RE
.br
.B \-r [20] 
.RS
To reduce the load on the X server the program generates several columns of pixels before scrolling the image. This flag sets the number of columns.
.RE
.br
.B \-R [0] 
.RS
Set the seed for the random number generator. A value of 0 causes the seed to be set from the clock.
.RE
.br
.B \-f [0.65] 
.RS
Set the fractal dimension of the surface. This should be in the range 0.5\-1.0.
.RE
.br
.B \-I [0.785] 
.RS
Set the angle of illumination.
.RE
.br
.B \-S [0.6] 
.RS
Set the vertical stretch of the surface.
.RE
.br
.B \-T [0.5] 
.RS
Set the vertical shidt of the surface.
.RE
.br
.B \-a [2.5] 
.RS
Set the Altitude of the viewpoint.
.RE
.br
.B \-p [4.0] 
.RS
Set the distance of the viewpoint from the front of the surface.
.RE
.br
.B \-g [string] 
.RS
Set the geometry of the window.
.RE
.br
.B \-d [string] 
.RS
Set the display.
.RE

.PP

.SH IDENTIFICATION
Author: S.Booth@ed.ac.uk



